### ISSUE TITLE
Mac OS X El Capitan not working!

### ISSUE THREAD

**Issue by TNAJanssen** [creaktive/iStat-Pro.wdgt#1]
![schermafbeelding 2015-06-16 om 10 50 28](https://cloud.githubusercontent.com/assets/2812277/8179220/86166e08-1415-11e5-93cb-4291a2afc479.png)

**Comment by creaktive** [comment]
Well, it was removed from MacOS for a reason, after all ¯\\\_(ツ)_/¯
